# Generated by Django 2.0.5 on 2018-06-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp_app', '0002_auto_20180613_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='energy',
            field=models.IntegerField(default=100),
        ),
    ]
