# Generated by Django 2.0.5 on 2018-06-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp_app', '0004_auto_20180618_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='event_one',
            new_name='event1',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='event_three',
            new_name='event2',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='event_two',
            new_name='event3',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='finals_questions',
            new_name='finals_count',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='quiz_one',
            new_name='quiz1',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='quiz_two',
            new_name='quiz2',
        ),
    ]
